[package]
name = "iot_sound_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
crossbeam = "0.8.2"
json = "0.12.4"
paho-mqtt = "0.11.1"

